#!/usr/bin/env sh

echo "Small Response Body:"
curl http://localhost:8080/
echo "\n\nEmpty Response:"
curl http://localhost:8080/empty
echo "\n\nBody Too Large:"
curl -H'Content-Length: 4000000000' http://localhost:8080/
echo "\n\nEcho Body:"
curl -XPOST http://localhost:8080/echo -d'Echo test'
echo "\n\nGet Header:"
curl http://localhost:8080/host
echo "\n\nIterate Headers:"
curl -H'User-Agent: test-ua' -H'Foo-Header: foo-bar' http://localhost:8080/headers
echo "\nStress Test keep-alive:"
ab -k -c 200 -n 100000 http://localhost:8080/ > keep-alive.bench
cat keep-alive.bench | grep Complete
cat keep-alive.bench 1>&2
echo "\nStress Test close:"
ab -c 20 -n 1000 http://localhost:8080/ > connection-close.bench
cat connection-close.bench | grep Complete
cat connection-close.bench 1>&2
echo "\nStress Test large body:"
dd if=/dev/urandom of=test.dat bs=52428800 count=1 2> /dev/null
ab -c 2 -n 10 -p test.dat http://localhost:8080/echo > large-file.bench
cat large-file.bench | grep Complete
cat large-file.bench 1>&2
rm test.dat *.bench
